carstore/views/store.py
import re
from typing_extensions import Self
from flask import Flask, request, template_rendered, Blueprint
from flask import url_for, redirect, flash
from flask import render_template
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from datetime import datetime
from numpy import identity, product
import random, string
from sqlalchemy import null
from link import *
import math
import base64
from api.sql import Member, Order_List, Product, Record, Cart
from datetime import datetime

store = Blueprint('carstore', __name__, template_folder='../templates')

@store.route('/', methods=['GET', 'POST'])
@login_required
def carstore():
    result = Product.count()
    count = math.ceil(result[0]/9)
    flag = 0
    
    if request.method == 'GET':
        if(current_user.role == 'manager'):
            flash('No permission')
            return redirect(url_for('manager.home'))

    if 'keyword' in request.args and 'page' in request.args:
        total = 0
        single = 1
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        search = request.values.get('keyword')
        keyword = search
        
        cursor.execute('SELECT * FROM PRODUCT WHERE model LIKE %s', ('%' + search + '%',))
        car_row = cursor.fetchall()
        car_data = []
        final_data = []
        
        for i in car_row:
            car = {
                '車輛編號': i[0],
                '車輛品牌': i[1],
                '車輛型號': i[2]
            }
            car_data.append(car)
            total = total + 1
        
        if(len(car_data) < end):
            end = len(car_data)
            flag = 1
            
        for j in range(start, end):
            final_data.append(car_data[j])
            
        count = math.ceil(total/9)
        
        return render_template('carstore.html', single=single, keyword=search, car_data=car_data, user=current_user.name, page=1, flag=flag, count=count)    

    #這裡是送進product.html
    elif 'pid' in request.args:
        pid = request.args['pid']
        data = Product.get_product(pid)
        
        brand = data[1]
        model = data[2]
        year = data[3]
        mileage = data[4]
        color = data[5]
        price = data[6]
        status = data[7]
        image = base64.b64encode(data[8]).decode('utf-8')  # 將二進制數據轉為 Base64 字串
        
        product = {
            '車輛編號': pid,
            '車輛品牌': brand,
            '車輛型號': model,
            '年分': year,
            '里程': mileage,
            '顏色': color,
            '租金': price,
            '車輛狀態': status,
            '車輛圖片': f"data:image/jpeg;base64,{image}"
        }

        return render_template('product.html', data = product, user=current_user.name)
    
    elif 'page' in request.args:
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        
        car_row = Product.get_all_product()
        car_data = []
        final_data = []
        
        for i in car_row:
            car = {
                '車輛編號': i[0],
                '車輛品牌': i[1],
                '車輛型號': i[2]
            }
            car_data.append(car)
            
        if(len(car_data) < end):
            end = len(car_data)
            flag = 1
            
        for j in range(start, end):
            final_data.append(car_data[j])
        
        return render_template('carstore.html', car_data=final_data, user=current_user.name, page=page, flag=flag, count=count)    
    
    elif 'keyword' in request.args:
        single = 1
        search = request.values.get('keyword')
        keyword = search
        cursor.execute('SELECT * FROM PRODUCT WHERE model LIKE %s', ('%' + search + '%',))
        car_row = cursor.fetchall()
        car_data = []
        total = 0
        
        for i in car_row:
            car = {
                '車輛編號': i[0],
                '車輛品牌': i[1],
                '車輛型號': i[2]
            }

            car_data.append(car)
            total = total + 1
            
        if(len(car_data) < 9):
            flag = 1
        
        count = math.ceil(total/9)    
        
        return render_template('carstore.html', keyword=search, single=single, car_data=car_data, user=current_user.name, page=1, flag=flag, count=count)    
    
    else:
        car_row = Product.get_all_product()
        car_data = []
        temp = 0
        for i in car_row:
            car = {
                '車輛編號': i[0],
                '車輛品牌': i[1],
                '車輛型號': i[2],
            }
            if len(car_data) < 9:
                car_data.append(car)
        
        return render_template('carstore.html', car_data=car_data, user=current_user.name, page=1, flag=flag, count=count)

# 會員購物車
@store.route('/cart', methods=['GET', 'POST'])
@login_required # 使用者登入後才可以看
def cart():
    # 以防管理者誤闖
    if request.method == 'GET':
        if (current_user.role == 'manager'):
            flash('No permission')
            return redirect(url_for('manager.home'))

    # 回傳有 pid 代表要加商品
    if request.method == 'POST':
        if "pid" in request.form:
            data = Cart.get_cart(current_user.id)

            if data is None:  # 假如購物車裡面沒有他的資料
                time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                Cart.add_cart(current_user.id, time)  # 幫他加一台購物車
                data = Cart.get_cart(current_user.id)

            tno = data[1]  # 取得交易編號
            pid = request.form.get('pid')  # 使用者想要購買的東西，使用 `request.form.get()` 來避免 KeyError
            if not pid:
                flash('Product ID is missing.')
                return redirect(url_for('carstore.cart'))  # 返回購物車頁面並顯示錯誤信息

            # 檢查購物車裡面有沒有商品
            product = Record.check_product(tno)
            # 取得商品價錢
            price = Product.get_product(pid)[6]

            # 如果購物車裡面沒有的話，把它加一個進去
            if product is None:
                start_date = request.form.get(f"{pid}_start") # 從form裡面拿取車時間
                end_date = request.form.get(f"{pid}_end") # 從form裡面拿還車時間
                Record.add_product({'pid': pid, 'tno': tno, 'saleprice': price, 'total': price, 'startdate':start_date, 'enddate':end_date})
            else:
                # 若購物車內已經有商品
                # existing_order = Record.get_record(tno)  
                # existing_pid = existing_order[0][1] # pid(已存在車輛編號)
                start_date = request.form.get(f"{pid}_start")
                end_date = request.form.get(f"{pid}_end")
                Record.delete_product(tno)
                Record.add_product({'pid': pid, 'tno': tno, 'saleprice': price, 'total': price, 'startdate':start_date, 'enddate':end_date})
                # Record.update_product({'pid': pid, 'tno': tno, 'amount': 0, 'total': price, 'startdate': start_date, 'enddate': end_date})
                print("已覆蓋原有訂單。")

        elif "delete" in request.form:
            pid = request.form.get('delete')
            tno = Cart.get_cart(current_user.id)[1]
            Member.delete_product(tno, pid)
            product_data = only_cart()
        #點擊繼續選車
        elif "user_edit" in request.form:
            tno = Cart.get_cart(current_user.id)[1]
            pid = Cart.get_pid(str(tno))
            start_date = request.form.get(f"{pid}_start") # 從form裡面拿取車時間
            end_date = request.form.get(f"{pid}_end") # 從form裡面拿還車時間
            if start_date and end_date: 
                change_order()
            else:
                pass
            return redirect(url_for('carstore.carstore'))
        #點擊下一步(到確認駕駛資訊)
        elif "buy" in request.form:
            tno = Cart.get_cart(current_user.id)[1]
            pid = Cart.get_pid(str(tno))
            start_date = request.form.get(f"{pid[0]}_start") # 從form裡面拿取車時間
            end_date = request.form.get(f"{pid[0]}_end") # 從form裡面拿還車時間

            if start_date and end_date:
                if(Record.reserve_recheck(tno,pid,start_date,end_date)):
                    flash("該時段已有人預訂!")
                    return redirect(url_for('carstore.cart'))
                else:
                    change_order()                
            else:
                flash("請選擇時間")
                return redirect(url_for('carstore.cart'))   
            return redirect(url_for('carstore.license'))    
        
        elif "undo" in request.form:
            return redirect(url_for('carstore.license'))  

        elif "order" in request.form:
            tno = Cart.get_cart(current_user.id)[1]
            total = Record.get_total_money(tno)
            Cart.clear_cart(current_user.id)

            time = str(datetime.now().strftime('%Y/%m/%d %H:%M:%S'))
            format = 'yyyy/mm/dd hh24:mi:ss'
            Order_List.add_order({'mid': current_user.id, 'ordertime': time, 'total': total, 'format': format, 'tno': tno})

            return render_template('complete.html', user=current_user.name)

    product_data = only_cart()
    if product_data == 0:
        return render_template('empty.html', user=current_user.name)
    else:
        return render_template('cart.html', data=product_data, user=current_user.name)

#點擊直接結帳後將購物車內商品送入order頁面
@store.route('/order')
def order():    
    data = Cart.get_cart(current_user.id)
    tno = data[1]

    product_row = Record.get_record(tno)
    product_data = []

    for i in product_row:
        model = Product.get_name(i[1])
        product = {
            '車輛編號': i[1],
            '車輛型號': model,
            '租金': i[3],
            '時數': i[6]
        }
        product_data.append(product)
    
    total = float(Record.get_total(tno))  # 將 Decimal 轉換為 float


    return render_template('order.html', data=product_data, total=total, user=current_user.name)

@store.route('/orderlist')
def orderlist():
    if "oid" in request.args :
        pass
    
    user_id = current_user.id

    data = Member.get_order(user_id)
    orderlist = []

    for i in data:
        temp = {
            '訂單編號': i[0],

carstore/templates/carstore.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}車輛導覽{% endblock title%}

{% block content%}
<br/>

{% with messages = get_flashed_messages() %}
{% if messages %}
  
<script language="javascript">

  alert('您沒有管理員的權限喔！');

</script>

{% endif %}
{% endwith %}

<div class="car_table container-xxl">

  <form class="d-flex col-sm-4" action="{{ url_for('carstore.carstore', keyword=1) }}">
    <div class="input-group">
    <span class="input-group-text" id="basic-addon1">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    </span>
    <input name='keyword' class="form-control me-2" type="search" placeholder="搜尋車輛" aria-label="Search">
    </div>
  </form><br/>
  <form method="post" action={{ url_for('carstore.cart' ) }}>
      
      
      {% for car in car_data %}
      {% if loop.index % 3 == 1 %}
      <div class="row">
      {% endif %}
      
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{car.車輛品牌}}</h5>
              <p class="card-text">{{car.車輛型號}}</p>
              
              <a href="{{ url_for('carstore.carstore', pid=car.車輛編號) }}" class="btn btn-outline-primary">查看車輛資訊</a>
              <button class="btn btn-outline-success" type="submit" value="{{car.車輛編號}}" name="pid" >預約</button>
            </div>
          </div>
        </div>

        {% if loop.index % 3 == 0 %}
        </div><br/>
        {% endif %}
            
      {% endfor %}
    </table>
  </form>


  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('carstore.carstore', page=page-1) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      {% for i in range(1, count+1) %}
      {% if single == 1 %}
      <li class="page-item"><a class="page-link" href="{{ url_for('carstore.carstore', keyword=keyword, page=i) }}">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{{ url_for('carstore.carstore', page=i) }}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      {% if flag == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('carstore.carstore', page=page+1) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>

{% endblock content%}

carstore/templates/cart.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}目前訂車資料{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>
<div class="container-xl">
  <br/>
  <h2 class="mb-4 text-center">選擇取車/還車時間</h2>
  <form method="post" action={{ url_for('carstore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>車輛編號</center></th>
        <th><center>車輛型號</center></th>
        <th><center>車輛租金/小時</center></th>
        <th><center>取車時間</center></th>
        <th><center>還車時間</center></th>
        <th><center>租用操作</center></th>
      </tr>
      {% for car in data %}
      <tr>
        <td> <center>{{ car.車輛編號 }}</center></td>
        <td> <center>{{ car.車輛型號 }}</center></td>
        <td> <center>{{ car.租金 }}</center></td>
        <td width="20%">
          <center>
            <!-- 開始日期與時間選擇器 -->
            <input class="form-control" type="datetime-local" id="{{ car.車輛編號 }}_start" name="{{ car.車輛編號 }}_start"
                   min="{{ today_date }}"  value="{{ car.取車時間 }}" onchange="validateDate('{{ car.車輛編號 }}')">
          </center>
        </td>
        <td width="20%">
          <center>
            <!-- 結束日期與時間選擇器 -->
            <input class="form-control" type="datetime-local" id="{{ car.車輛編號 }}_end" name="{{ car.車輛編號 }}_end"
                   min="{{ today_date }}" value="{{ car.還車時間 }}" onchange="validateDate('{{ car.車輛編號 }}') ">
          </center>
        </td>
        <td>
          <center>
            <button class="btn btn-danger" type="submit" value="{{car.車輛編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ car.車輛型號 }}\' 嗎？'))">
              刪除
            </button>
          </center>
        </td>
      </tr>
      {% endfor %}  
    </table>

    <center>
      <div class="option">
        <button class="btn btn-primary" type="submit" name="user_edit" >繼續選車</button>
        <button class="btn btn-success" type="submit" name="buy" >下一步</button>
      </div>  
    </center> 

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
                {% for category, message in messages %}
                    <span style="color: red;">{{ message }}</span>
                {% endfor %}
        {% endif %}
    {% endwith %}

  </form>

</div>

<script>
  function validateDate(carId) {
    const startInput = document.getElementById(carId + '_start');
    const endInput = document.getElementById(carId + '_end');

    // 如果結束時間小於開始時間，則提示錯誤並清空結束時間
    if (endInput.value && startInput.value && (endInput.value < startInput.value)) {
      alert('結束時間不能小於開始時間');
      endInput.value = '';
    }
  }

  // 設定當前日期和時間的最小值，並將時區設為台灣 (UTC+8)
  document.querySelectorAll('input[type="datetime-local"]').forEach(input => {
    const now = new Date();
    // 以台灣時區計算
    now.setHours(now.getHours() - now.getTimezoneOffset() / 60);
    input.min = now.toISOString().slice(0, 16);
  }); 
</script>

{% endblock content%}

carstore/templates/complete.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 下單完成 {% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>

<div class="container-xxl">
  <center>
    <img width="30%" height="30%" src="../static/img/order_success.png">
  </center>
  <center>
    <h4>下單完成！</h4>
  </center>
  <center>
    
      <a href="{{ url_for('carstore.carstore') }}">
        <button class="btn btn-outline-success" style="width:30%;">
          回租車行
        </button>
      </a>
      
  </center>
  
  
</div>

{% endblock content%}

carstore/templates/empty.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}購物車清單{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>

<div class="container-xxl">
  <center>
    <img width="50%" height="50%" src="../static/img/empty_cart.png">
  </center>
  <center>
    
      <a href="{{ url_for('carstore.carstore') }}">
        <button class="btn btn-outline-success" style="width:30%;">
          繼續購物
        </button>
      </a>
      
  </center>
  
  
</div>

{% endblock content%}

carstore/templates/frontstage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand" href="#">&nbsp;中山租車</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('carstore.carstore') }}">車輛導覽</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('carstore.cart') }}">目前訂車資料</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('carstore.orderlist') }}">歷史訂單</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('carstore.userinfo') }}">會員資料</a>
                    </li>
                </ul>

                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>

                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <li style="color:white;list-style-type:none">使用者：{{user}}</li>
                </ul>

                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

carstore/templates/license.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}carstore{% endblock title%}

{% block content%}

<br/>
<div class="d-flex justify-content-center align-items-center">
    <div class="container mt-5">
        <h2 class="mb-4 text-center">確認駕駛資訊</h2>
        <form  method='post' action={{ url_for('carstore.license') }}>
            <!-- 駕照號碼 -->
            <div class="mb-3">
                <label for="licenseNumber" class="form-label">駕照號碼</label>
                <input type="text" class="form-control" name="license_number" placeholder="請輸入駕照號碼" value="{{ license_number }}">
            </div>

            <!-- 聯絡電話 -->
            <div class="mb-3">
                <label for="phoneNumber" class="form-label">聯絡電話</label>
                <input type="tel" class="form-control" name="phone_number" placeholder="請輸入聯絡電話" value="{{ phone_number }}" minlength="10" maxlength="10" >
            </div>
            
            <!-- 地址 -->
             <div class="mb-3">
                <label for="address" class="form-label">住家地址</label>
                <input type="text" class="form-control" name="address" placeholder="請輸入住家地址" value="{{ address }}" >
            </div>

            <!-- 按鈕區塊 -->
            <center> 
              <div class="option">
                <button class="btn btn-primary" type="submit" name="undo">上一步</button>
                <button class="btn btn-success" type="submit" name="pay">前往付款</button>
              </div>
            </center>
        </form>
    </div>
</div>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
            {% for category, message in messages %}
                <span style="color: red;">{{ message }}</span>
            {% endfor %}
    {% endif %}
{% endwith %}
{% endblock content%}

carstore/templates/orderlist.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}歷史訂單{% endblock title%}

{% block content %}
<!-- <form method="post" action="#"> -->
  {% for i in data %}
  <div class="modal fade" id="staticBackdrop{{i.訂單編號}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">訂單細項列表</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <div class="mb-3">
                    <table class="table table-bordered">
                      <tr>
                        <th width="10%"><center>車型</center></th>
                        <th width="30%"><center>車輛租金/小時</center></th>
                        <th width="20%"><center>預訂時數</center></th>
                        <th width="20%"><center>取車時間</center></th>
                        <th width="20%"><center>還車時間</center></th>
                      </tr>
                      
                      {% for j in detail %}
                      {% if j.訂單編號 == i.訂單編號 %}
                      <tr>
                        <td> <center>{{ j.車輛型態 }}</center></td>
                        <td> <center>{{ j.租金 }}</center></td>
                        <td> <center>{{ j.天數 }}</center></td>
                        <td> <center>{{ j.取車時間 }}</center></td>
                        <td> <center>{{ j.還車時間 }}</center></td>
                      </tr>
                      {% endif %}
                      {% endfor %}
                    </table>
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal" style="width:30%;">回訂單</button>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
<!-- </form> -->



<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('carstore.orderlist') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>訂單編號</center></th>
        <th><center>訂單總價</center></th>
        <th><center>訂單時間</center></th>
        <th><center>查看訂單</center></th>
      </tr>
      {% for i in data %}
      <tr>
        <td> <center>{{ i.訂單編號 }}</center></td>
        <td> <center>{{ i.訂單總價 }}</center></td>
        <td> <center>{{ i.訂單時間 }}</center></td>
        <td width="20%">
          <center>
            <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{i.訂單編號}}">
              查看訂單細項
            </button>
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>

  </form>
</div>

{% endblock content %}