backstage/views/analysis.py
from flask import render_template, Blueprint
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import Analysis

analysis = Blueprint('analysis', __name__, template_folder='../templates')

@analysis.route('/dashboard')
@login_required
def dashboard():
    revenue = []
    dataa = []
    for i in range(1,13):
        row = Analysis.month_price(i)

        if not row:
            revenue.append(0)
        else:
            for j in row:
                revenue.append(j[1])
        
        row = Analysis.month_count(i)
        
        if not row:
            dataa.append(0)
        else:
            for k in row:
                dataa.append(k[1])
        
    row = Analysis.brand_sale()
    datab = []
    for i in row:
        temp = {
            'value': i[0],
            'name': i[1]
        }
        datab.append(temp)
    
    row = Analysis.member_sale()
    
    datac = []
    nameList = []
    counter = 0
    
    for i in row:
        counter = counter + 1
        datac.append(i[0])
    for j in row:
        nameList.append(j[2])
    
    counter = counter - 1
    
    row = Analysis.member_sale_count()
    countList = []
    
    for i in row:
        countList.append(i[0])
        
    return render_template('dashboard.html', counter = counter, revenue = revenue, dataa = dataa, datab = datab, datac = datac, nameList = nameList, countList = countList, user=current_user.name)

backstage/views/manager.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import *
import imp, random, os, string
import psycopg2
from werkzeug.utils import secure_filename
from flask import current_app
from io import BytesIO

UPLOAD_FOLDER = 'static/product'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'pjp', 'pjpeg', 'jfif'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

manager = Blueprint('manager', __name__, template_folder='../templates')

def config():
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    config = current_app.config['UPLOAD_FOLDER'] 
    return config

@manager.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return redirect(url_for('manager.productManager'))

@manager.route('/productManager', methods=['GET', 'POST'])
@login_required
def productManager():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('index'))
        
    if 'delete' in request.values:
        pid = request.values.get('delete')
        data = Record.delete_check(pid)
        
        if(data != None):
            flash('failed')
        else:
            #data = Product.get_product(pid)
            Product.delete_product(pid)
    
    elif 'edit' in request.values:
        pid = request.values.get('edit')
        return redirect(url_for('manager.edit', pid=pid))
    
    car_data = car()
    return render_template('productManager.html', car_data = car_data, user=current_user.name)

def car():
    car_row = Product.get_all_product()
    car_data = []
    for i in car_row:
        car = {
            '車輛編號': i[0],
            '車輛品牌': i[1],
            '車輛型號': i[2],
            '出廠年份': i[3],
            '總里程': i[4],
            '車輛顏色': i[5],
            '價格': i[6],
        }
        car_data.append(car)
    return car_data

@manager.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        if (request.values.get('submit')=='true'):
            data = ""
            #pid = "0"
            while(data != None):
                number = str(random.randrange( 1000, 10000))
                en = random.choice(string.ascii_letters) + random.choice(string.ascii_letters) + random.choice(string.ascii_letters)
                pid = en.upper() + '-' + number
                data = Product.get_product(pid)
            
            brand = request.values.get('brand')
            model = request.values.get('model')
            year = request.values.get('year')
            mileage = request.values.get('mileage')
            color = request.values.get('color')
            price = request.values.get('price')
            status = request.values.get('status')
            file = request.files.get('file')
            image_data = None

            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                image_data = file.read()

            # 檢查是否正確獲取到所有欄位的數據
            if brand is None or price is None or model is None or year is None or mileage is None or color is None or status is None:
                flash('所有欄位都是必填的，請確認輸入內容。')
                return redirect(url_for('manager.productManager'))

            # 檢查欄位的長度
            if len(brand) < 1 or len(price) < 1:
                flash('商品名稱或價格不可為空。')
                return redirect(url_for('manager.productManager'))

            # if (len(pname) < 1 or len(price) < 1):
            #     return redirect(url_for('manager.productManager'))
            
            Product.add_product(
                {
                'pid' : pid,
                'brand' : brand,
                'model' : model,
                'year' : year,
                'mileage' : mileage,
                'color' : color,
                'price' : price,
                'status': status,
                'image': image_data
                }
            )
            return redirect(url_for('manager.productManager'))

    return render_template('productManager.html')

@manager.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('bookstore'))

    if request.method == 'POST':
        if(request.values.get('submit')=='true'):
            file = request.files.get('file')
            pid = request.values.get('pid')
            image_data = None
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                # 如果有上傳圖片，將其保存並轉換為二進制數據
                image_data = file.read()
            else:
                image_data = Product.get_image(pid)
            
            Product.update_product(
                {
                'brand' : request.values.get('brand'),
                'model' : request.values.get('model'),
                'year' : request.values.get('year'), 
                'mileage' : request.values.get('mileage'),
                'color' : request.values.get('color'),
                'price' : request.values.get('price'),
                'status' : request.values.get('status'),
                'pid' : pid,
                'image': image_data
                }
            )       
        
        return redirect(url_for('manager.productManager'))

    else:
        product = show_info()
        return render_template('edit.html', data=product)


def show_info():
    pid = request.args['pid']
    data = Product.get_product(pid)
    brand = data[1]
    model = data[2]
    year = data[3]
    mileage = data[4]
    color = data[5]
    price = data[6]
    status = data[7]
    image = data[8]

    product = {
        '車輛編號': pid,
        '車輛品牌': brand,
        '車輛型號': model,
        '出廠年份': year,
        '總里程': mileage,
        '車輛顏色': color,
        '價格': price,
        '車輛敘述': status
    }
    return product


@manager.route('/orderManager', methods=['GET', 'POST'])
@login_required
def orderManager():
    if request.method == 'POST':
        pass
    else:
        order_row = Order_List.get_order()
        order_data = []
        for i in order_row:
            order = {
                '訂單編號': i[0],
                '訂購人': i[1],
                '訂單總價': i[2],
                '訂單時間': i[3]
            }
            order_data.append(order)
            
        orderdetail_row = Order_List.get_orderdetail()
        order_detail = []

        for j in orderdetail_row:
            orderdetail = {
                '訂單編號': j[0],
                '車輛型號': j[1],
                '車輛價格': j[2],
                '租用時數': j[3],
                '租車時間': j[4],
                '還車時間': j[5]
            }
            order_detail.append(orderdetail)

    return render_template('orderManager.html', orderData = order_data, orderDetail = order_detail, user=current_user.name)

backstage/templates/backstage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.1.2/echarts.min.js" integrity="sha512-ppWbHq6q2f7HAwS481w6qikuC0XEeBnmkRg6KWnWg3zSIbJwWWBgsCDMAxzSB7SVqXzWwSYQ2s8TSJKjnaikMg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }
    
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand" href="#">&nbsp;中山租車後台管理系統</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.productManager') }}">商品管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.orderManager') }}">訂單管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('analysis.dashboard') }}">資料分析</a>
                    </li>
                </ul>



                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>
                    <li style="color:white;list-style-type:none">管理者：{{user}}</li>
                </ul>
                <div class="d-flex">
                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
                </div>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

backstage/templates/dashboard.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block title %}後台資料分析{% endblock title%}
{% block content %}

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <!-- Dashboard -->
  <div id="dashboard">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">訂單數量分析</button>
        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">車輛出租量分類</button>
        <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">消費總額排名</button>        
      </div>      
    </nav>
  </div>
  <br/>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <center> 
        <div id="maina" class="container-fluid" style="width:1200px;height:500px"></div>
      </center>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <center>
        <div id="mainb" class="container-fluid" style="width: 600px;height:500px"></div>
      </center>
    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <center>
        <div id="mainc" class="container-fluid" style="width: 1200px;height:500px"></div>
      </center>
    </div>
  </div>
</div>

<script>
  // 以長條圖與折線圖分析各月訂單
  var chartDoma = document.getElementById('maina');
  var myCharta = echarts.init(chartDoma);
  var data = {{revenue|tojson}};
  var count = {{dataa|tojson}};
  var optiona = {
    title: {
      text: '各月訂單數量分析'
    },
    tooltip: {
      trigger: 'axis',
        axisPointer: {
            type: 'shadow' // 坐标轴指示器，默认为直线，可选 'line' | 'shadow'
        }
    },
    legend: {
      data: ['訂單總額', '訂單數量'], // 图例显示两条系列
        show: true
    },
    xAxis: {
      data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
    },
    yAxis: {
      type: 'value',
        name: '金額/數量', // y轴名称
        axisLabel: {
            formatter: '{value}'
        }
    },
    series: [{
      name: '出租總額',
      type: 'bar',
      // symbol: 'circle',
      symbolSize: 16,
      data: data,
      markPoint: {
        data: [
          {type: 'max', name: '出租總額最高月份'},
          {type: 'min', name: '出租總額最低月份'}
        ]
      },
      label: {
        show: true,
        position: 'top',
        textStyle: {
          fontSize: 15
        }
      }
    },
    {
      name: '訂單數量',
      type: 'bar',
      // symbol: 'circle',
      symbolSize: 16,
      data: count,
      markPoint: {
        data: [
          {type: 'max', name: '訂單數量最多月份'},
          {type: 'min', name: '訂單數量最少月份'}
        ]
      },
      label: {
        show: true,
        position: 'top',
        textStyle: {
          fontSize: 15
        }
      }
    }
    ],
    legend: {
      show: true
    },
  };

  // 以圓餅圖分析書本銷量
  var data = {{datab|tojson}};
  var legendData = data.map(item => item.name);
  var chartDomb = document.getElementById('mainb');
  var myChartb = echarts.init(chartDomb);
 
  var optionb = {
    title: {
      text: '各廠牌出租量分析',
      left: 'center',
      top: 'center'
    },
    tooltip: {
                trigger: 'item',
                formatter: '{b} : {c} ({d}%)'
    },
    legend: {
      orient: 'vertical',
      x: 'left',
      data: legendData
    },
    series: [
      {
        name: '品牌',
        type: 'pie',
        data: data,          
        radius: ['40%', '70%']
      }
    ]
  };

  // 使用動態長條圖查看消費總額最多的使用者
  var chartDomc = document.getElementById('mainc');
  var myChartc = echarts.init(chartDomc);
  var data = {{datac|tojson}};
  var nameList = {{nameList|tojson}};
  // var counter = {{counter|tojson}};
  var countList = {{countList|tojson}};
  var optionc = {
    title: {
      text: '使用者消費排名'
    },
    xAxis: {
      max: 'dataMax'
    },
    yAxis: {
      type: 'category',
      data: nameList,
      inverse: true,
      animationDuration: 300,
      animationDurationUpdate: 300,
      max: 3
    },
    tooltip: {},
    series: [
      {
        realtimeSort: true,
        name: '消費總額',
        type: 'bar',
        data: data,
        label: {
          show: true,
          position: 'right',
          valueAnimation: true
        }
      },
      {
        realtimeSort: true,
        name: '訂單總數',
        type: 'bar',
        data: countList,
        label: {
          show: true,
          position: 'right',
          valueAnimation: true
        }
      }
      ],
    legend: {
      show: true
    },
    animationDuration: 3000,
    animationDurationUpdate: 3000,
    animationEasing: 'linear',
    animationEasingUpdate: 'linear'
  };

  function run() {
    myChartc.setOption({
      series: [
        {
          type: 'bar',
          data
        }
      ]
    });
  }

  setTimeout(function() {
    run();
  }, 0);
        
  setInterval(function() {
    update();
  }, 3000);

  optiona && myCharta.setOption(optiona);
  optionb && myChartb.setOption(optionb);
  optionc && myChartc.setOption(optionc);
      
</script>

{% endblock content %}

backstage/templates/manager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<div class="btn_div">
  <h1 class="book_title left">31 Lab Book Store</h1>
  <a href="{{ url_for('analysis.dashboard') }}"  title="資料分析"><img class="cart" src="{{ url_for('static', filename='./img/dashboard.png') }}"></a>
  <a href="{{ url_for('logout') }}"  title="登出"><img class="logout" src="{{ url_for('static', filename='./img/logout.png') }}"></a>
</div>
<div class="btn_div">
  <p class="welcome">歡迎 , 管理者：{{user}}</p>
</div>
{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>

{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'faild' %}
  
<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<div class="book_table">
  <form method='post' action={{ url_for('manager') }} >
    <table cellpadding="10" border='3'>
      <tr>
        <th>商品編號</th>
        <th>商品名稱</th>
        <th>商品售價</th>
        <th>商品類別</th>
        <th></th>
        <th></th>
      </tr>
      {% for book in book_data %}
      <tr>
        <td> {{ book.商品編號 }}</td>
        <td> {{ book.商品名稱 }}</td>
        <td> {{ book.商品售價 }}</td>
        <td> {{ book.商品類別 }}</td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="edit">修改
          </button>
        </td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ book.商品名稱 }}\' 嗎？'))">
            刪除
          </button>
        </td>
      </tr>
      {% endfor %}
    </table>
      <div class="book_table">
        <a href={{ url_for('add')}}><button value="new" name="new" type="button"> 上架新商品</button></a>
      </div>
    </form>

</div>

{% endblock content%}

backstage/templates/productManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 商品管理 {% endblock title %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>


{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'failed' %}
  
<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<script>
    $(document).ready(function(){
        $("#keyword").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#product tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
&nbsp;
&nbsp;
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋商品" aria-label="Search">
    </div>
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        新增商品
    </button>
</div>

<form method="post" enctype=multipart/form-data action={{ url_for('manager.add') }}>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新增商品</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="inputbrand" class="form-label">車輛廠牌</label>
                        <input type="text" class="form-control" id="inputbrand" name="brand" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputmodel" class="form-label">車輛型號</label>
                        <input type="text" class="form-control" id="inputmodel" name="model" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputyear" class="form-label">出廠年份</label>
                        <input type="number" class="form-control" id="inputyear" name="year" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputmileage" class="form-label">里程</label>
                        <input type="number" class="form-control" id="inputmileage" name="mileage" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputcolor" class="form-label">車輛顏色</label>
                        <input type="text" class="form-control" id="inputcolor" name="color" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputprice" class="form-label">車輛價格(小時)</label>
                        <input type="number" class="form-control" id="inputprice" name="price" required>
                    </div>
                    <!-- <div class="mb-3">
                        <label for="inputProductCategory" class="form-label">商品種類</label>
                        <select id="inputProductCategory" class="form-select" name="category" required>
                            <option selected disabled value="">請選擇類型</option>
                            <option value="BOOK">BOOK</option>
                            <option value="CD">CD</option>
                            <option value="DVD">DVD</option>
                        </select>
                    </div> -->
                    <div class="mb-3">
                        <label for="inputstatus" class="form-label">車輛敘述</label>
                        <textarea class="form-control" id="inputstatus" name="status" required></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductImg" class="form-label">車輛圖片</label><br/>
                        <input type="file" name="file" id="file-uploader" accept="image/jpeg, image/png, image/jpg" data-target="file-uploader" required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-success" name="submit" value="true">確定新增</button>
                </div>
            </div>
        </div>
    </div>
</form>

<br/>

<div class="container-xxl">

<form method='post' action={{ url_for('manager.productManager') }} >
<table id="manager" class="table table-bordered">
    <thead>
        <tr>
            <th width="10%"><center>車輛編號</center></th>
            <th width="15%"><center>車輛品牌</center></th>
            <th width="15%"><center>車輛型號</center></th>
            <th width="10%"><center>出廠年份</center></th>
            <th width="10%"><center>總里程</center></th>
            <th width="10%"><center>車輛顏色</center></th>
            <th width="10%"><center>價格(小時)</center></th>
            <th colspan="2"><center>資料操作</center></th>        
        </tr>
    </thead>
    <tbody id="product">
    {% for i in car_data %}
        <tr>
            <td><center>{{ i.車輛編號 }}</center></td>
            <td><center>{{ i.車輛品牌 }}</center></td>
            <td><center>{{ i.車輛型號 }}</center></td>
            <td><center>{{ i.出廠年份 }}</center></td>
            <td><center>{{ i.總里程 }}</center></td>
            <td><center>{{ i.車輛顏色 }}</center></td>
            <td><center>{{ i.價格 }}</center></td>
            <td><center><button type="submit" value="{{i.車輛編號}}" name="edit" class="btn btn-success">編輯商品</button></center></td>
            <td><center><button type="submit" value="{{i.車輛編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ i.車輛編號 }}\' 嗎？'))" class="btn btn-danger">刪除商品</button></center></td>
        </tr>
    {% endfor %}
    </tbody>
    
</table>
</form>


</div>

<script>
    function have_product(){
      alert('有使用者有使用到這筆資料，所以不能刪除');
    }
</script>

{% endblock content %}